### ISSUE TITLE
`SessionJapUserStore`的`save()`方法参数问题

### ISSUE THREAD

**Issue by Vector6662** [fujieid/jap#5]
`SessionJapUserStore`的save()方法我认为似乎有一些问题。方法体中的这行代码：
```java
JapTokenHelper.saveUserToken(japUser.getUserId(), token);
```
需要`japUser`实例的Id作为参数，但有时`japUser`并没有设置Id属性，比如[实现japuserservice接口](https://justauth.plus/quickstart/jap-simple.html#%E5%AE%9E%E7%8E%B0-japuserservice-%E6%8E%A5%E5%8F%A3)中模拟的数据就没有模拟其中的Id属性。
没有设置Id更多是开发者的疏忽，但是目前的报错似乎不是很友好。

**Comment by zhangyd-c** [comment]
已处理，将在 1.0.4 版本发布：https://github.com/fujieid/jap/commit/17dfee27850804131879d111133178b5995c27ca

**Comment by Vector6662** [comment]
好滴！😁

**Comment by zhangyd-c** [comment]
1.0.4 已经发布
