### ISSUE TITLE
你们的官方文档页面内存暴涨，挂几分钟页面甚至直接OOM

### ISSUE THREAD

**Issue by VioletCoding** [fujieid/jap#8]
![image](https://user-images.githubusercontent.com/37135917/129673017-ef81fd5c-bef5-4781-a833-0c990fbbd4d7.png)

**Comment by zhangyd-c** [comment]
遇到这个问题先刷新页面吧，怀疑是这个vuepress主题的问题，目前已经在更换 vuepress 主题了。替换完成后会在这条issue里回复给你，感谢关注

**Comment by zhangyd-c** [comment]
新版文档站已上线，目前测试良好，感谢支持：https://justauth.plus/

该主题请参考：https://github.com/xugaoyi/vuepress-theme-vdoing
