### ISSUE TITLE
bug: checkAuthenticateConfig方法逻辑

### ISSUE THREAD

**Issue by Vector6662** [fujieid/jap#9]
`com.fujieid.jap.core.strategy.AbstractJapStrategy`类中的方法`checkAuthenticateConfig`似乎存在一些逻辑问题。
```java
protected void checkAuthenticateConfig(AuthenticateConfig sourceConfig, Class<?> targetConfigClazz) throws JapException {
        if (ObjectUtil.isNull(sourceConfig)) {
            throw new JapException(JapErrorCode.MISS_AUTHENTICATE_CONFIG);
        }
        if (!ClassUtil.isAssignable(sourceConfig.getClass(), targetConfigClazz)) {
            throw new JapException("Unsupported parameter type, please use " + ClassUtil.getClassName(targetConfigClazz, true) + ", a subclass of AuthenticateConfig");
        }
    }
```
我认为这里的逻辑应该是检查`sourceConfig`所属的类应该是`targetConfigClazz`本身或是子类。在我的代码中`sourceConfig`实参为`SimpleProperties`，**它是`SimpleConfig`的子类**。所以这里调用`ClassUtil.isAssignable(...)`似乎两个参数的位置写反了，因为我描述的这个情况正好满足`ClassUtil.isAssignable(...)`方法说明上的第二点：**2、目标类型是原类型的父类**。
![image](https://user-images.githubusercontent.com/35756575/132131653-189163ab-5b0b-40e9-b12f-5c5e1e22a396.png)

同时我也进行了测试：

![image](https://user-images.githubusercontent.com/35756575/132131511-0221ef0b-fd3f-4f50-bfd3-b4c2ec01894f.png)

当源和目标交换一下位置后才是正确的：
![image](https://user-images.githubusercontent.com/35756575/132131560-33944807-2875-479f-982b-dfd8479415be.png)

**Comment by zhangyd-c** [comment]
AuthenticateConfig 是父类，targetConfigClazz 是继承了 AuthenticateConfig 的字类，ClassUtil.isAssignable 是用来判断 【目标类型是原类型的父类】，即 isAssignable 方法的第一个参数是第二个参数的父类，简单理解就是父类放第一个参数，字类放第二个参数，按照你的逻辑，SimpleConfig 为父类，SimpleProperties 是 SimpleConfig 的字类，正确使用方式是 ClassUtil.isAssignable(SimpleConfig.class, SimpleProperties.class)。 我感觉让你疑惑的应该是 `checkAuthenticateConfig(AuthenticateConfig sourceConfig, Class<?> targetConfigClazz)` 这个方法的参数命名。这个方法校验的是 targetConfigClazz 是否是 sourceConfig 的字类。
